### ISSUE TITLE
Is "avoid using String#+" still valid in the era of frozen_string_literal

### ISSUE THREAD

**Issue by latentflip** [github/rubocop-github#28]
I was just digging through the styleguide, and spotted that at least in `github/github` where we fail the build if `frozen_string_literal: true` is not set, the suggested code won't actually run.

Should we update the guidance here? Or be more clear that _large_ is the keyword here, and guide as to how to correctly opt out of frozen_string_literal (I don't actually know how to)

---

> Avoid using String#+ when you need to construct large data chunks. Instead, use String#<<. Concatenation mutates the string instance in-place and is always faster than String#+, which creates a bunch of new string objects.
 
```
# good and also fast
html = ""
html << "<h1>Page title</h1>"

paragraphs.each do |paragraph|
  html << "<p>#{paragraph}</p>"
end
```

**Comment by rmosolgo** [comment]
👋  I guess this project is pretty quiet. I agree this cop needs an update, I'll take a look as part of #29

**Comment by kytrinyx** [comment]
> guide as to how to correctly opt out of frozen_string_literal

At the top of the file, you can add a comment:

```
# rubocop:disable Style/FrozenStringLiteralComment
```

This would be in place of:

```
# frozen_string_literal: true
```
