### ISSUE TITLE
Rails cops being removed in RuboCop 0.72

### ISSUE THREAD

**Issue by MrChrisW** [github/rubocop-github#44]
### Summary

Add [rubocop-rails](https://rubygems.org/gems/rubocop-rails) as Gem dependency when upgrading to the next **0.72** release of [rubocop](https://rubygems.org/gems/rubocop/versions).

https://github.com/github/rubocop-github/blob/7bccddc437ff907aadedd5b8604522849c91aaeb/rubocop-github.gemspec#L13-L15

### Details

Rails cops will be removed from RuboCop 0.72, therefore we need to use the `rubocop-rails` gem instead.

**Comment by kytrinyx** [comment]
@MrChrisW I went a head and bumped rubocop, and introduced both rubocop-rails and rubocop-performance in the gem dependencies. This should now be good on master.

**Comment by MrChrisW** [comment]
Thanks @kytrinyx 🎉
