### ISSUE TITLE
Metrics/Lin eLength has the wrong namespace - should be Layout

### ISSUE THREAD

**Issue by joshRpowell** [github/rubocop-github#54]
Change in rubocop 0.78.0: https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#changes-2

Needs update here https://github.com/github/rubocop-github/blob/5bd3ab3f55c8f45179dbcacb1803b5f492d7ca1f/config/_default_shared.yml#L186

**Comment by AstmDesign** [comment]
i'm facing the same warning `.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout` 
what I should do to remove this warning?

**Comment by cupnoodle** [comment]
@AstmDesign  , in your rubcop.yml file, replace`Metrics/LineLength` with `Layout/LineLength`

**Comment by AstmDesign** [comment]
@cupnoodle thank you, it's fixed the warning

**Comment by kytrinyx** [comment]
This is fixed on master. We ended up having to pin Rubocop pretty hard, and incrementally fix warnings along the way, since so many of the rubocop pre-1.0 minor version updates introduce breaking changes.

**Comment by KingsleyMcSimon** [comment]
Thanks @cupnoodle, i had the same issue as @AstmDesign above but following what you suggested solved the issue for me.

**Comment by RichardsonWTR** [comment]
Thanks, @cupnoodle.   
Besides, here's the reference for anyone facing other obsolete errors: https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/config_obsoletion.rb

**Comment by use931** [comment]
[](url)
