### ISSUE TITLE
Explain why `def self.foo` is preferred over `class << self`

### ISSUE THREAD

**Issue by alexanderadam** [github/rubocop-github#7]
As your styleguide recommends

```ruby
class TestClass
  # bad
  class << self
    def first_method
      # body omitted
    end

    def second_method_etc
      # body omitted
    end
  end

  # good
  class << self
    attr_accessor :per_page
    alias_method :nwo, :find_by_name_with_owner
  end

  def self.first_method
    # body omitted
  end

  def self.second_method_etc
    # body omitted
  end
end
```

I was wondering *why*. If it's just a matter of taste for you: fine, please write this in the styleguide as well.

It isn't obvious here why you are preferring this because especially in cases with many class methods the block and therefore also the additional indention give a good *visual hint* that methods are *encapsulated* and belong together. They share a similar context and blocks are the usual way of creating contexts.

Besides from that it can also help to avoid to have class methods spread over a file. It is easier (at least for people I know) to have class methods together in one place than having a bunch of instance methods in between.

The Eigenclass context also makes sense in your example as `per_page` and `first_method` both will create class methods. But in your example just `attr_accessor` and `alias_method` are using the Eigenclass context whereas `first_method` and `second_method_etc` give an 'defined from the outside' feeling.

These points makes it more understandable for me to follow [bbatsovs / rubocops styleguide](https://github.com/bbatsov/ruby-style-guide#classes--modules) which says
```ruby
  # Also possible and convenient when you
  # have to define many class methods.
  class << self
    def first_method
      # body omitted
    end

    def second_method_etc
      # body omitted
    end
  end
```

**Comment by rmosolgo** [comment]
I don't _agree_ with the preference expressed in the guide, but I think I understand the issue. Consider this Ruby code: 

```ruby 
class A 
  class << self 
    attr_accessor :some_attribute 
  end 
end 

class B < A 
end 
```

As far as I know, that's the _only way_ to support usage like this: 

```ruby 
A.some_attribute = :value_1 
B.some_attribute # => nil 
B.some_attribute = :value_2 
A.some_attribute # => :value_1 
```

I mean, using a class variable would cause it to be shared by `A` and `B`, which we don't want. 

Does that sound right to you? Is there another way to implement that snippet above? 

I think the same thing is true for `alias`, it only works for class methods inside `class << self`. 

So, I don't agree with the preference, but I think that explains the difference, does that make sense?

**Comment by alexanderadam** [comment]
@rmosolgo 
I just wrote about

```ruby
  def self.foo
    …
  def self.bar
    …
  def self.baz
    …
```

vs

```ruby
  class << self
    def foo
      …
    def bar
      …
    def baz
      …
```

And I didn't mention `attr_accessor` or `alias` at all‽

**Comment by maxim** [comment]
I second this, would actually love to have an optional cop for enforcing the `class << self` style as opposed to `self.foo`. Summary of benefits:

- indent serves as the visual que
- helps keep all class methods grouped together
- searching `def foo` returns both class and instance methods
- adding class-level code requires `class << self` anyway, might as well use it for methods too

**Comment by alexanderadam** [comment]
I'm sorry. I just recognized that the title of the issue was actually the inverse to what I wrote to in the description :see_no_evil: 
I'm sorry in case that this was the cause of the misunderstanding here.

By the way, the particular text snipped I referenced here, is this sentence

> [Avoid `class << self` except when necessary, e.g. single accessors and aliased attributes.](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#classes)

**Comment by mmahalwy** [comment]
I agree. I think the cop should avoid having both `class << self` and `def self.blah` in the same file

**Comment by composerinteralia** [comment]
RuboCop added a cop for this in 2020 that can be configured either way: https://github.com/rubocop/rubocop/pull/8381. So I'd say this one is mostly personal preference, and our style guide now matches the default configuration in RuboCop.
