### ISSUE TITLE
I don't _agree_ with the preference expressed in the guide, but I think I understand the issue. Consider this Ruby code:

### ISSUE THREAD

**Issue by mulham99** [github/rubocop-github#70]
I don't _agree_ with the preference expressed in the guide, but I think I understand the issue. Consider this Ruby code: 

```ruby 
class A 
  class << self 
    attr_accessor :some_attribute 
  end 
end 

class B < A 
end 
```

As far as I know, that's the _only way_ to support usage like this: 

```ruby 
A.some_attribute = :value_1 
B.some_attribute # => nil 
B.some_attribute = :value_2 
A.some_attribute # => :value_1 
```

I mean, using a class variable would cause it to be shared by `A` and `B`, which we don't want. 

Does that sound right to you? Is there another way to implement that snippet above? 

I think the same thing is true for `alias`, it only works for class methods inside `class << self`. 

So, I don't agree with the preference, but I think that explains the difference, does that make sense?

_Originally posted by @rmosolgo in https://github.com/github/rubocop-github/issues/7#issuecomment-418865787_

**Comment by composerinteralia** [comment]
RuboCop added a cop in 2020 that covers this: [rubocop/rubocop#8381](https://github.com/rubocop/rubocop/pull/8381). Our style guide matches the default for this cop, and otherwise it's mostly a matter of preference.
