### ISSUE TITLE
Misleading linting when passing a variable to render `locals:`

### ISSUE THREAD

**Issue by glortho** [github/rubocop-github#92]
When you pass a variable instead of an explicit hash to render, Rubocop complains that "render must be used with a string literal or an instance of a Class". 

Linter complains:

```ruby
render("some/template", locals: hash_of_locals)
```

Linter does not complain:

```ruby
render("some/template", locals: {**hash_of_locals})
```

Assuming there is no particular issue with passing in a hash variable to locals, it seems like maybe there is just a parsing issue here? Or...if that is in fact an issue in latest Rails, maybe the message just needs updating.

**Comment by just-joshing** [comment]
Just hit this myself for developing security center at enterprise.
Thanks for the workaround.

**Comment by jhawthorn** [comment]
Please don't use `locals: {**hash_of_locals}`

> Assuming there is no particular issue with passing in a hash variable to locals

Please don't do this. The linter exists to prevent exactly this pattern.
